name: Kotlin CI

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: ./gradlew spotlessCheck